### ISSUE TITLE
horrible typo in current web version

### ISSUE THREAD

**Issue by kbuzzard** [hhu-adam/NNG4#14]
Right now [live on the website](https://adam.math.hhu.de/#/g/hhu-adam/NNG4/world/Tutorial/level/3) we have 

![typo](https://github.com/hhu-adam/NNG4/assets/31867827/9117f568-5227-406c-821c-d473a74e3b93)

This is a horrible typo in the docs (`succ a` -> `succ b`) because it's confusing. It was fixed on `main` in [this commit](https://github.com/hhu-adam/NNG4/commit/378a156bbeeeff505f86a8b2f4702438d48841ce). Can this be deployed? And is there a clever way of stopping this happening in future?

**Comment by abentkamp** [comment]
I've deployed it. (hopefully without breaking anything else?)

I don't think such typos can be avoided. What do you have in mind?

**Comment by kbuzzard** [comment]
I was wondering whether we could get Lean to write the text statement from the Lean statement. But having now written a bunch of levels I see that this is unfeasible, I agree that we need the flexibility to make typos.
