### ISSUE TITLE
Let `rfl` close iffs as well as equalities

### ISSUE THREAD

**Issue by kmill** [hhu-adam/NNG4#18]
I saw this todo: https://github.com/hhu-adam/NNG4/blob/7ecd27ead91a4255ac78ee3f928f92a0ed2e2457/Game/Tactic/Rfl.lean#L24

Here is some mildly tested code to implement being able to close iffs as well as equalities. The `Lean.MVarId.iffRefl` function is adapted from `Lean.MVarId.refl` with some simplifications (for example, no need for kernel defeq checking).
```lean
/--
Close given goal using `Iff.refl`.
-/
def Lean.MVarId.iffRefl (mvarId : MVarId) : MetaM Unit := do
  mvarId.withContext do
    mvarId.checkNotAssigned `iffRefl
    let targetType ← mvarId.getType'
    let some (lhs, rhs) := Expr.app2? targetType ``Iff
      | throwTacticEx `iffRefl mvarId m!"iff expected"
    unless ← isDefEq lhs rhs do
      throwTacticEx `iffRefl mvarId
        m!"lhs{indentD lhs}\nis not definitionally equal to rhs{indentD rhs}"
    mvarId.assign (.app (mkConst ``Iff.refl) lhs)

@[tactic MyNat.rfl] def evalRfl : Tactic := fun _ =>
  liftMetaTactic fun mvarId => withReducible do
    let targetType ← mvarId.getType'
    match targetType.getAppFn with
      | .const ``Eq .. => mvarId.refl
      | .const ``Iff .. => mvarId.iffRefl
      | _ => throwTacticEx `rfl mvarId "expecting an equality or iff"
    pure []
```
I decided to create an issue rather than submitting a PR since I'm being lazy and didn't test this in the full environment (sorry). I was just looking at how `rfl` worked in NNG4 since Kevin Buzzard mentioned something about it on Zulip.

**Comment by joneugster** [comment]
Thank you Kyle! I will have a look at this next week and incorporate your code.

**Comment by joneugster** [comment]
Thanks again @kmill ! Finally got around to add this
