### ISSUE TITLE
able to use `zero_mul` to prove itself

### ISSUE THREAD

**Issue by haifron** [hhu-adam/NNG4#27]
I found this by accident in the middle of proving zero_mul, and have tried on a new session and it works, as shown in the below screenshot.

![image](https://github.com/hhu-adam/NNG4/assets/91282973/61b9b599-439c-4067-9fab-38de187b3dcd)

when I was proving it in my initial attempt I did at least get an error, though it didn't prevent the proof from continuing:

![image](https://github.com/hhu-adam/NNG4/assets/91282973/7db965e0-5682-4f25-91c3-f49a1ef95b45)

**Comment by joneugster** [comment]
The initial error reported here should now be (partially) fixed:

- on "regular" it yields an error
- on "relaxed" it yields a warning

However, there is an underlying problem that needs to be addressed here. I'm going to open an issue explaining this on the lean4game-repo, as I don't have a trivial solution in mind: [lean4game#117](https://github.com/leanprover-community/lean4game/issues/117)
