### ISSUE TITLE
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by jameshfisher** [hhu-adam/NNG4#4]
Hi! I was hoping to use this to run a tutorial, but when I visit https://adam.math.hhu.de/, I get the error: `GET https://adam.math.hhu.de/bundle.js net::ERR_CONTENT_LENGTH_MISMATCH 206 (Partial Content)`. This happens on Chrome and Firefox.

**Comment by joneugster** [comment]
Hi Jim,

Sorry for that, minor problems with the server that are fixed now! Let me know if you still experience problems.

**Comment by joneugster** [comment]
leanprover-community/lean4game#80

**Comment by jameshfisher** [comment]
Amazing! Thank you! 🙏
