### ISSUE TITLE
Question: How do you run lean4 on mdbook?

### ISSUE THREAD

**Issue by Seasawher** [hhu-adam/NNG4#7]
(I don't know where the appropriate repository is, so I'll comment here)

If you mouse over the lean code in the mdbook of Natural Number Game, you can see the type.
How is this implemented?

If nothing is configured, the mdbook playground will only be able to execute rust code.

**Comment by abentkamp** [comment]
I don't even know how to use mdbook. I don't think we have done anything special about that.

**Comment by joneugster** [comment]
Is this about [Chris Lovett Natural Numbers book](https://lovettsoftware.com/NaturalNumbers/TutorialWorld.lean.html)? That is completely independent of this repo, so I have no idea either. But you find the corresponding github repo & author here: https://github.com/lovettchris/NaturalNumbers

This repo contains the code for the interactive lean4 game at https://adam.math.hhu.de/#/g/hhu-adam/NNG4

**Comment by Seasawher** [comment]
Thank you so much!
